INFO:     Started server process [88824]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:47776 - "GET /admin/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:49624 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:49624 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:34722 - "POST /smart_recommender/user/register/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/app/route/user.py", line 14, in create_new_user
    db_user = get_user(db, user.username)  # Check if the user already exists
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/app/logic/user.py", line 7, in get_user
    return db.query(UserInDB).filter(UserInDB.username == username).first()
           ^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2952, in query
    return self._query_cls(entities, self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 275, in __init__
    self._set_entities(entities)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 288, in _set_entities
    coercions.expect(
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/sql/coercions.py", line 388, in expect
    insp._post_inspect
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2722, in _post_inspect
    self._check_configure()
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2399, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4215, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4256, in _do_configure_registries
    mapper._post_configure_properties()
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2416, in _post_configure_properties
    prop.init()
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/interfaces.py", line 589, in init
    self.do_init()
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1642, in do_init
    self._setup_entity()
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1854, in _setup_entity
    self._clsregistry_resolve_name(argument)(),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/clsregistry.py", line 516, in _resolve_name
    rval = d[token]
           ~^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/util/_collections.py", line 345, in __missing__
    self[key] = val = self.creator(key)
                      ^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/clsregistry.py", line 463, in _access_cls
    return _determine_container(key, decl_class_registry[key])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/clsregistry.py", line 409, in _determine_container
    value = value.attempt_get([], key)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/clsregistry.py", line 219, in attempt_get
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Multiple classes found for path "UserProfile" in the registry of this declarative base. Please use a fully module-qualified path.
INFO:     127.0.0.1:48628 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:48644 - "POST /smart_recommender/user/register/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/app/route/user.py", line 14, in create_new_user
    db_user = get_user(db, user.username)  # Check if the user already exists
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/app/logic/user.py", line 7, in get_user
    return db.query(UserInDB).filter(UserInDB.username == username).first()
           ^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2952, in query
    return self._query_cls(entities, self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 275, in __init__
    self._set_entities(entities)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 288, in _set_entities
    coercions.expect(
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/sql/coercions.py", line 388, in expect
    insp._post_inspect
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2722, in _post_inspect
    self._check_configure()
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2399, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4215, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4252, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[UserInDB(users)]'. Original exception was: Multiple classes found for path "UserProfile" in the registry of this declarative base. Please use a fully module-qualified path.
INFO:     127.0.0.1:48652 - "POST /smart_recommender/auth/login/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/app/route/auth.py", line 19, in login_for_access_token
    user = authenticate_user(db, form_data.username, form_data.password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/app/logic/auth.py", line 25, in authenticate_user
    user = get_user(db, username)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/app/logic/user.py", line 7, in get_user
    return db.query(UserInDB).filter(UserInDB.username == username).first()
           ^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2952, in query
    return self._query_cls(entities, self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 275, in __init__
    self._set_entities(entities)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 288, in _set_entities
    coercions.expect(
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/sql/coercions.py", line 388, in expect
    insp._post_inspect
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2722, in _post_inspect
    self._check_configure()
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2399, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4215, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/jenish/Desktop/StuckAI/stuckAIforTravel/venv/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4252, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[UserInDB(users)]'. Original exception was: Multiple classes found for path "UserProfile" in the registry of this declarative base. Please use a fully module-qualified path.
INFO:     127.0.0.1:57148 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:53502 - "GET /admin/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:53502 - "GET /admin/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:53502 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:35282 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:43086 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:43086 - "GET /openapi.json HTTP/1.1" 200 OK
